language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.4
      env: TOXENV=python3.4
    - python: 3.5
      env: TOXENV=python3.5
    - python: 3.6
      env: TOXENV=python3.6

os:
  - linux

install:
  - pip install setuptools --upgrade
  - pip install tox
  - pip install coveralls

script: 
  - tox
  - python setup.py test --addopts "-v --cov pytablewriter --cov-report term-missing"

after_success:
  - coveralls

notifications:
  slack:
    secure: JTq9Gq60gZj1krX7zNNaHTUGaFhhw/gahi6OBi3aJGKrg1gxk6L+XcBu+0hKrwCUVlzAXoapkzhDSWILSR2eSq+GDzpLY0g/CZWq2jVLjnTh8YtiShYU4TiQcTOh3vVncvCKvyw+GI/CgVcvYPTFNgdH9LX09r8MEXfJmjZ5mU1mgdPRWZ2UW9C5dK7P5th+pAK0SF+MNrAaF/3/kzNO49PGZsYkTnVcKiaKdTO6YJ3JAHS9L+XLuLhAbqjAkv4gErB3OkezpEo4gwaepwtvGZfsmLQzCcagbmav3Qifnv/7XklJymXIbQ4cC10sbYCstQmXV8AkGm354I0CX1wG21PHRE0T4jtxsxbZ8nAUZ9MDW64G7bLvEYa7Kabg3e64oLfvRBLY+vQdm7km/kmdyC6Wx47xH5vtZtkC9ORILNmaI3OtKw6eyTK0s3vV/DW0IBz1ENHJWO1zZceSpujNpju9Nwgvtt3r9GpcZziq3IoRPfo/FOdwXeTO1Loh8ExpQZoRdPXFGGXd0lp/8FyE1+g2in5gl6BRau8vGiWQLWWiKMG8Hgine+fSuhkQd6b38yqbC1dpIc2td5sdgtz7ovB3PErk5CRFfq2UGZWbcfACosRaMEKAhbg8fvutWgCFloLnF/gA4cYB0uXVIfsFzGqNDAyPVo0OEKbxB+VFkjM=

deploy:
  provider: pypi
  user: vmmhypervisor
  password:
    secure: iBbAMn5j8SjIdFK3zrsd6phox2Q87atYyTrzwieJeUFLfVzeQt9N65iMa7ZY6vq/oecawDWRfQ9UUsV6M/FEKqb+jENF4sUMZklmV3TkgC++DzSfjcJLbTplyzsqPhPU2cWoVDZz556dMhSHDDn4tRfoBbcUJ6cNj3eyBo2wAC0EIG0oiiPH5ltII8STuPeXKaCBS5RjUySjG0WQ4007iB8EVbvBFfXs9Q9FRNFmKIv+NZTRqqPunNJSLqcHxvNtaPIy4OvKbTExtB8KSNizQlhn6xzbGd2NI8lM+neFHxrbV64tJ6O6+Ml10MR72JT/hTNqBZ8JxmjxWBkf0F65ddwbLn+Q6WB3aOlHYC5e9Xqt8Y9i3DGyW4S8jDC5sMBbxnGQAUuAOD7AWS6wKsvDqjxH9+JuqcFwat64V5M7ZEeNkW5c0oBgQJ6fj4jArWogltg0lZWZ5qjxIqvMvNz+BqV7vJRK0cX6BjIMQK1VdAu0oChHxrMm9jEBgBCcJjNYKLT8Yh7DQBN49QqH47i2OxBxj+iw4K4wEZq7OhjVPnl6utF0PSr8xRxhbZovXVPfIxez/gwqG7zrKo455Wj+bs48m7qTZUJmrxzzC1UjIKemoQOy+EmSJb3e7Lvor2XRi0sMmin5cwH+vFGT2zPiSepyuooOd46JS7gSSw2oh/E=
  on:
    tags: true
    repo: thombashi/pytablewriter
    branch: master
    python: 3.6
  distributions: "sdist bdist_wheel"
